### ISSUE TITLE
[BUG] Crash when clicking "Open website" button on Linux

### ISSUE THREAD

**Issue by fschrempf** [iakmds/buhocms#12]
**Describe the bug**
After clicking the "Open website" button, the app shows a blank screen and the log shows an exception trace. 

<details><summary><h3>Trace</h3></summary>

```console
flutter: type '_Map<String, dynamic>' is not a subtype of type 'String'
flutter: #0      Preferences.getRecentSitePaths (package:buhocms/src/utils/preferences.dart:171)
flutter: #1      _OpenWebsiteState.recentSitePaths (package:buhocms/src/pages/open_website.dart:346)
flutter: #2      _OpenWebsiteState.build (package:buhocms/src/pages/open_website.dart:387)
flutter: #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:5080)
flutter: #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4968)
flutter: #5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
flutter: #6      Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
flutter: #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124)
flutter: #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #11     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377)
flutter: #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #14     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
flutter: #16     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
flutter: #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #20     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377)
flutter: #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #23     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377)
flutter: #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #26     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
flutter: #28     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
flutter: #29     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
flutter: #31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124)
flutter: #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377)
flutter: #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
flutter: #39     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
flutter: #40     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
flutter: #42     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124)
flutter: #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #45     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #46     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377)
flutter: #47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #48     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
flutter: #50     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
flutter: #51     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #52     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
flutter: #53     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124)
flutter: #54     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #55     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #56     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
flutter: #58     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
flutter: #59     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #60     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
flutter: #61     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124)
flutter: #62     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #64     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #65     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377)
flutter: #66     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #67     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
flutter: #69     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
flutter: #70     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #71     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
flutter: #72     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124)
flutter: #73     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #75     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #76     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377)
flutter: #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #78     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
flutter: #80     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
flutter: #81     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #82     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
flutter: #83     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124)
flutter: #84     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #85     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #86     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
flutter: #88     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
flutter: #89     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #90     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
flutter: #91     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124)
flutter: #92     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #94     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
flutter: #96     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #97     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
flutter: #98     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
```
</details>

**Expected behavior**
App doesn't crash.

**Steps to reproduce the behavior:**
1. Start app
2. Click on  `Open website`
3. See error

**Other information:**
 - OS: Manjaro Linux 
```
>>> cat /etc/lsb-release                                                                                                                                                                                                  
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=22.1.0
DISTRIB_CODENAME=Talos
DISTRIB_DESCRIPTION="Manjaro Linux"
```

Please let me know if you need any further debugging information. Thanks!

**Comment by fschrempf** [comment]
By the way: This doesn't happen with v0.5.0, only with the latest v0.6.0.

**Comment by iakmds** [comment]
Hi there,
thank you a lot. I was actually aware of this issue, but I thought I had fixed it...

As a workaround for now, you can reset the app preferences at the top of the Settings page (you can export the current ones and take a look at that file, so that you can remember some settings). I'll try to fix it in a point release

**Comment by iakmds** [comment]
By the way, does it still give the same error message?

**Comment by gsegit** [comment]
Ok, unter Manjaro hab ich dasselbe, aber keine Fehlermeldung. Einfach nur ne graue Seite-

**Comment by iakmds** [comment]
> Ok, unter Manjaro hab ich dasselbe, aber keine Fehlermeldung. Einfach nur ne graue Seite-

@gsegit Könntest du deine Einstellungen exportieren und diese .json-Datei hier schicken? Dann könnte ich sie importieren und gucken, wie ich das fixen könnte

**Comment by fschrempf** [comment]
Thanks a lot! It seems to work for me now with v0.6.1!
