### ISSUE TITLE
[BUG] Open website presents gray screen

### ISSUE THREAD

**Issue by deining** [iakmds/buhocms#14]
**Describe the bug**

Select `Open website` from menu:

**Screenshots**

![grafik](https://user-images.githubusercontent.com/18169566/232747044-72e5908c-a5ba-4124-b21e-9cd31a743620.png)

A gray window is shown:

![grafik](https://user-images.githubusercontent.com/18169566/232747338-e14055dd-44f6-4a2b-92dc-669186cb5aed.png)

I'm stuck here.

**Other information:**
 - OS: Windows 11
 - Version 22H2

**Comment by iakmds** [comment]
Thank you for the issue. 

Could you export your current preferences and send that .json file here? I could import it and try to see how I can fix it

**Comment by deining** [comment]
> Thank you for the issue.
> 
> Could you export your current preferences and send that .json file here? I could import it and try to see how I can fix it

I see the same error on my Linux system.
This is my `preferences.json`:

```json
{
  "language": "",
  "themeMode": "system",
  "colorScheme": 27,
  "pageIndex": 1,
  "currrentFileIndex": -1,
  "navigationSize": 64.0,
  "fileNavigationSize": 64.0,
  "onboardingCompleted": true,
  "ssg": "hugo",
  "sitePostPath": "/home/andreas/WebSites/test",
  "recentSitePaths": {},
  "currentPath": "/home/andreas/WebSites/test/content",
  "currentFile": null,
  "isGUIMode": true,
  "isFrontmatterGUIMode": true,
  "sortMode": "name",
  "frontMatterAddList": "{\"title\":\"typeString\",\"date\":\"typeDate\",\"draft\":\"typeBool\",\"tags\":\"typeList\"}",
  "draggableMode": false,
  "tabs": null
}
```

And this is the stack trace:

```
flutter: type '_Map<String, dynamic>' is not a subtype of type 'String'
flutter: #0      Preferences.getRecentSitePaths (package:buhocms/src/utils/preferences.dart:171)
flutter: #1      _OpenWebsiteState.recentSitePaths (package:buhocms/src/pages/open_website.dart:346)
flutter: #2      _OpenWebsiteState.build (package:buhocms/src/pages/open_website.dart:387)
flutter: #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:5080)
flutter: #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4968)
flutter: #5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
flutter: #6      Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
flutter: #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124)
flutter: #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #11     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377)
flutter: #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #14     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
flutter: #16     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
flutter: #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #20     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377)
flutter: #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #23     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377)
flutter: #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #26     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
flutter: #28     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
flutter: #29     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
flutter: #31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124)
flutter: #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377)
flutter: #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
flutter: #39     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
flutter: #40     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
flutter: #42     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124)
flutter: #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #45     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #46     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377)
flutter: #47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #48     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
flutter: #50     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
flutter: #51     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #52     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
flutter: #53     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124)
flutter: #54     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #55     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #56     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
flutter: #58     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
flutter: #59     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #60     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
flutter: #61     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124)
flutter: #62     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #64     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #65     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377)
flutter: #66     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #67     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
flutter: #69     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
flutter: #70     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #71     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
flutter: #72     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124)
flutter: #73     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #75     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #76     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377)
flutter: #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #78     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
flutter: #80     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
flutter: #81     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #82     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
flutter: #83     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124)
flutter: #84     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #85     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #86     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
flutter: #88     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
flutter: #89     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #90     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
flutter: #91     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124)
flutter: #92     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #94     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
flutter: #96     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #97     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
flutter: #98     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
```

**Comment by iakmds** [comment]
Thank you a lot!

The issue should be solved with the new release [0.6.1](https://github.com/iakmds/buhocms/releases/tag/v0.6.1) :smiley: 
Let me know if everything is working now!

**Comment by fschrempf** [comment]
Duplicate of https://github.com/iakmds/buhocms/issues/12

**Comment by deining** [comment]
>  Let me know if everything is working now!

Yes, the issue seems to be resolved. Thanks for your fix.
